# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fa39f72727886e16e697d941d8ab683cb54b3f41027942e575e429538011849a4cdcb226b9e051c05abcfdf032ff4744cb7d58733eaad33cbacf877fc7753e5

test:
  secret_key_base: 2419b3445d08a23852dd1a61d844ae1f0fac9551e5319c33d6e4c9f1c950b9a9432a54de3080877cd390b692fb51447a68257b94263acda32a335980cd0549cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
